# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'form.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_sortingGui(object):
    def setupUi(self, sortingGui):
        sortingGui.setObjectName("sortingGui")
        sortingGui.resize(1662, 872)
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(sortingGui)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(20, 20, 686, 831))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_connection = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.label_connection.setEnabled(True)
        font = QtGui.QFont()
        font.setBold(True)
        self.label_connection.setFont(font)
        self.label_connection.setTextFormat(QtCore.Qt.AutoText)
        self.label_connection.setAlignment(QtCore.Qt.AlignCenter)
        self.label_connection.setObjectName("label_connection")
        self.verticalLayout.addWidget(self.label_connection)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_hardware_status = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.label_hardware_status.setEnabled(True)
        font = QtGui.QFont()
        font.setBold(True)
        self.label_hardware_status.setFont(font)
        self.label_hardware_status.setTextFormat(QtCore.Qt.AutoText)
        self.label_hardware_status.setAlignment(QtCore.Qt.AlignCenter)
        self.label_hardware_status.setObjectName("label_hardware_status")
        self.horizontalLayout_6.addWidget(self.label_hardware_status, 0, QtCore.Qt.AlignLeft)
        self.label_status_roboter = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.label_status_roboter.setEnabled(True)
        font = QtGui.QFont()
        font.setBold(True)
        self.label_status_roboter.setFont(font)
        self.label_status_roboter.setTextFormat(QtCore.Qt.AutoText)
        self.label_status_roboter.setAlignment(QtCore.Qt.AlignCenter)
        self.label_status_roboter.setObjectName("label_status_roboter")
        self.horizontalLayout_6.addWidget(self.label_status_roboter, 0, QtCore.Qt.AlignRight)
        self.gridLayout.addLayout(self.horizontalLayout_6, 1, 1, 1, 1)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.button_dobot_homing = QtWidgets.QPushButton(self.verticalLayoutWidget_3)
        self.button_dobot_homing.setObjectName("button_dobot_homing")
        self.horizontalLayout_4.addWidget(self.button_dobot_homing)
        self.button_dobot_standby = QtWidgets.QPushButton(self.verticalLayoutWidget_3)
        self.button_dobot_standby.setObjectName("button_dobot_standby")
        self.horizontalLayout_4.addWidget(self.button_dobot_standby)
        self.gridLayout.addLayout(self.horizontalLayout_4, 0, 1, 1, 1)
        self.button_connect_Hardware = QtWidgets.QPushButton(self.verticalLayoutWidget_3)
        self.button_connect_Hardware.setObjectName("button_connect_Hardware")
        self.gridLayout.addWidget(self.button_connect_Hardware, 0, 0, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_object_detection_method = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.label_object_detection_method.setEnabled(True)
        font = QtGui.QFont()
        font.setBold(True)
        self.label_object_detection_method.setFont(font)
        self.label_object_detection_method.setTextFormat(QtCore.Qt.AutoText)
        self.label_object_detection_method.setAlignment(QtCore.Qt.AlignCenter)
        self.label_object_detection_method.setObjectName("label_object_detection_method")
        self.horizontalLayout_3.addWidget(self.label_object_detection_method)
        self.radio_classic = QtWidgets.QRadioButton(self.verticalLayoutWidget_3)
        self.radio_classic.setObjectName("radio_classic")
        self.buttonGroup = QtWidgets.QButtonGroup(sortingGui)
        self.buttonGroup.setObjectName("buttonGroup")
        self.buttonGroup.addButton(self.radio_classic)
        self.horizontalLayout_3.addWidget(self.radio_classic, 0, QtCore.Qt.AlignHCenter)
        self.radio_yoloV7 = QtWidgets.QRadioButton(self.verticalLayoutWidget_3)
        self.radio_yoloV7.setChecked(True)
        self.radio_yoloV7.setObjectName("radio_yoloV7")
        self.buttonGroup.addButton(self.radio_yoloV7)
        self.horizontalLayout_3.addWidget(self.radio_yoloV7)
        self.gridLayout.addLayout(self.horizontalLayout_3, 1, 0, 1, 1)
        self.label_status_camera = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.label_status_camera.setEnabled(True)
        font = QtGui.QFont()
        font.setBold(True)
        self.label_status_camera.setFont(font)
        self.label_status_camera.setTextFormat(QtCore.Qt.AutoText)
        self.label_status_camera.setAlignment(QtCore.Qt.AlignCenter)
        self.label_status_camera.setObjectName("label_status_camera")
        self.gridLayout.addWidget(self.label_status_camera, 3, 1, 1, 1, QtCore.Qt.AlignRight)
        spacerItem = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 4, 0, 1, 1)
        self.label_seperator_connection = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_seperator_connection.sizePolicy().hasHeightForWidth())
        self.label_seperator_connection.setSizePolicy(sizePolicy)
        self.label_seperator_connection.setMinimumSize(QtCore.QSize(30, 0))
        self.label_seperator_connection.setObjectName("label_seperator_connection")
        self.gridLayout.addWidget(self.label_seperator_connection, 4, 3, 1, 1)
        self.label_camera_connection = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_camera_connection.sizePolicy().hasHeightForWidth())
        self.label_camera_connection.setSizePolicy(sizePolicy)
        self.label_camera_connection.setMinimumSize(QtCore.QSize(30, 0))
        self.label_camera_connection.setMaximumSize(QtCore.QSize(30, 16777215))
        self.label_camera_connection.setObjectName("label_camera_connection")
        self.gridLayout.addWidget(self.label_camera_connection, 3, 3, 1, 1)
        self.label_dobot_connection = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_dobot_connection.sizePolicy().hasHeightForWidth())
        self.label_dobot_connection.setSizePolicy(sizePolicy)
        self.label_dobot_connection.setMinimumSize(QtCore.QSize(30, 0))
        self.label_dobot_connection.setObjectName("label_dobot_connection")
        self.gridLayout.addWidget(self.label_dobot_connection, 1, 3, 1, 1)
        self.label_conveyor_connection = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_conveyor_connection.sizePolicy().hasHeightForWidth())
        self.label_conveyor_connection.setSizePolicy(sizePolicy)
        self.label_conveyor_connection.setMinimumSize(QtCore.QSize(30, 0))
        self.label_conveyor_connection.setObjectName("label_conveyor_connection")
        self.gridLayout.addWidget(self.label_conveyor_connection, 2, 3, 1, 1)
        self.label_status_conveyor = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.label_status_conveyor.setEnabled(True)
        font = QtGui.QFont()
        font.setBold(True)
        self.label_status_conveyor.setFont(font)
        self.label_status_conveyor.setTextFormat(QtCore.Qt.AutoText)
        self.label_status_conveyor.setAlignment(QtCore.Qt.AlignCenter)
        self.label_status_conveyor.setObjectName("label_status_conveyor")
        self.gridLayout.addWidget(self.label_status_conveyor, 2, 1, 1, 1, QtCore.Qt.AlignRight)
        self.label_status_seperator = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.label_status_seperator.setEnabled(True)
        font = QtGui.QFont()
        font.setBold(True)
        self.label_status_seperator.setFont(font)
        self.label_status_seperator.setTextFormat(QtCore.Qt.AutoText)
        self.label_status_seperator.setAlignment(QtCore.Qt.AlignCenter)
        self.label_status_seperator.setObjectName("label_status_seperator")
        self.gridLayout.addWidget(self.label_status_seperator, 4, 1, 1, 1, QtCore.Qt.AlignRight)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_contour_method = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.label_contour_method.setEnabled(True)
        font = QtGui.QFont()
        font.setBold(True)
        self.label_contour_method.setFont(font)
        self.label_contour_method.setTextFormat(QtCore.Qt.AutoText)
        self.label_contour_method.setAlignment(QtCore.Qt.AlignCenter)
        self.label_contour_method.setObjectName("label_contour_method")
        self.horizontalLayout_5.addWidget(self.label_contour_method, 0, QtCore.Qt.AlignLeft)
        self.radio_contour_cut = QtWidgets.QRadioButton(self.verticalLayoutWidget_3)
        self.radio_contour_cut.setObjectName("radio_contour_cut")
        self.horizontalLayout_5.addWidget(self.radio_contour_cut, 0, QtCore.Qt.AlignLeft)
        self.gridLayout.addLayout(self.horizontalLayout_5, 2, 0, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        spacerItem1 = QtWidgets.QSpacerItem(20, 30, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.label_phases = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        font = QtGui.QFont()
        font.setBold(True)
        self.label_phases.setFont(font)
        self.label_phases.setTextFormat(QtCore.Qt.AutoText)
        self.label_phases.setAlignment(QtCore.Qt.AlignCenter)
        self.label_phases.setObjectName("label_phases")
        self.verticalLayout.addWidget(self.label_phases)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_data_collection = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_data_collection.sizePolicy().hasHeightForWidth())
        self.label_data_collection.setSizePolicy(sizePolicy)
        self.label_data_collection.setMinimumSize(QtCore.QSize(30, 0))
        self.label_data_collection.setObjectName("label_data_collection")
        self.gridLayout_2.addWidget(self.label_data_collection, 1, 2, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.check_feature_area = QtWidgets.QCheckBox(self.verticalLayoutWidget_3)
        self.check_feature_area.setObjectName("check_feature_area")
        self.gridLayout_3.addWidget(self.check_feature_area, 0, 0, 1, 1)
        self.check_feature_aspect = QtWidgets.QCheckBox(self.verticalLayoutWidget_3)
        self.check_feature_aspect.setObjectName("check_feature_aspect")
        self.gridLayout_3.addWidget(self.check_feature_aspect, 0, 2, 1, 1)
        self.check_feature_color = QtWidgets.QCheckBox(self.verticalLayoutWidget_3)
        self.check_feature_color.setObjectName("check_feature_color")
        self.gridLayout_3.addWidget(self.check_feature_color, 0, 1, 1, 1)
        self.check_feature_length = QtWidgets.QCheckBox(self.verticalLayoutWidget_3)
        self.check_feature_length.setObjectName("check_feature_length")
        self.gridLayout_3.addWidget(self.check_feature_length, 0, 3, 1, 1)
        self.check_feature_hu = QtWidgets.QCheckBox(self.verticalLayoutWidget_3)
        self.check_feature_hu.setObjectName("check_feature_hu")
        self.gridLayout_3.addWidget(self.check_feature_hu, 1, 0, 1, 1)
        self.check_feature_extent = QtWidgets.QCheckBox(self.verticalLayoutWidget_3)
        self.check_feature_extent.setObjectName("check_feature_extent")
        self.gridLayout_3.addWidget(self.check_feature_extent, 1, 1, 1, 1)
        self.check_feature_solidity = QtWidgets.QCheckBox(self.verticalLayoutWidget_3)
        self.check_feature_solidity.setObjectName("check_feature_solidity")
        self.gridLayout_3.addWidget(self.check_feature_solidity, 1, 2, 1, 1)
        self.horizontalLayout.addLayout(self.gridLayout_3)
        self.gridLayout_2.addLayout(self.horizontalLayout, 3, 1, 1, 1)
        self.label_sorting = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_sorting.sizePolicy().hasHeightForWidth())
        self.label_sorting.setSizePolicy(sizePolicy)
        self.label_sorting.setMinimumSize(QtCore.QSize(30, 0))
        self.label_sorting.setObjectName("label_sorting")
        self.gridLayout_2.addWidget(self.label_sorting, 6, 2, 1, 1)
        self.Button_Start_User_Feedback = QtWidgets.QPushButton(self.verticalLayoutWidget_3)
        self.Button_Start_User_Feedback.setObjectName("Button_Start_User_Feedback")
        self.gridLayout_2.addWidget(self.Button_Start_User_Feedback, 3, 0, 1, 1)
        self.button_sorting = QtWidgets.QPushButton(self.verticalLayoutWidget_3)
        self.button_sorting.setObjectName("button_sorting")
        self.gridLayout_2.addWidget(self.button_sorting, 6, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.radio_2d = QtWidgets.QRadioButton(self.verticalLayoutWidget_3)
        self.radio_2d.setChecked(True)
        self.radio_2d.setObjectName("radio_2d")
        self.buttonGroup_2 = QtWidgets.QButtonGroup(sortingGui)
        self.buttonGroup_2.setObjectName("buttonGroup_2")
        self.buttonGroup_2.addButton(self.radio_2d)
        self.horizontalLayout_2.addWidget(self.radio_2d)
        self.radio_3d = QtWidgets.QRadioButton(self.verticalLayoutWidget_3)
        self.radio_3d.setObjectName("radio_3d")
        self.buttonGroup_2.addButton(self.radio_3d)
        self.horizontalLayout_2.addWidget(self.radio_3d)
        self.combo_clustering_method = QtWidgets.QComboBox(self.verticalLayoutWidget_3)
        self.combo_clustering_method.setObjectName("combo_clustering_method")
        self.combo_clustering_method.addItem("")
        self.combo_clustering_method.addItem("")
        self.combo_clustering_method.addItem("")
        self.combo_clustering_method.addItem("")
        self.horizontalLayout_2.addWidget(self.combo_clustering_method)
        self.gridLayout_2.addLayout(self.horizontalLayout_2, 6, 1, 1, 1)
        self.SortingType = QtWidgets.QComboBox(self.verticalLayoutWidget_3)
        self.SortingType.setObjectName("SortingType")
        self.SortingType.addItem("")
        self.SortingType.addItem("")
        self.SortingType.addItem("")
        self.gridLayout_2.addWidget(self.SortingType, 1, 1, 1, 1)
        self.label_data_loading = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_data_loading.sizePolicy().hasHeightForWidth())
        self.label_data_loading.setSizePolicy(sizePolicy)
        self.label_data_loading.setMinimumSize(QtCore.QSize(30, 0))
        self.label_data_loading.setObjectName("label_data_loading")
        self.gridLayout_2.addWidget(self.label_data_loading, 3, 2, 1, 1)
        self.button_stop = QtWidgets.QPushButton(self.verticalLayoutWidget_3)
        self.button_stop.setObjectName("button_stop")
        self.gridLayout_2.addWidget(self.button_stop, 7, 0, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem2, 8, 0, 1, 1)
        self.button_load_and_cluster_data = QtWidgets.QPushButton(self.verticalLayoutWidget_3)
        self.button_load_and_cluster_data.setObjectName("button_load_and_cluster_data")
        self.gridLayout_2.addWidget(self.button_load_and_cluster_data, 5, 0, 1, 1)
        self.button_data_collection = QtWidgets.QPushButton(self.verticalLayoutWidget_3)
        self.button_data_collection.setObjectName("button_data_collection")
        self.gridLayout_2.addWidget(self.button_data_collection, 1, 0, 1, 1)
        self.label_clustering = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_clustering.sizePolicy().hasHeightForWidth())
        self.label_clustering.setSizePolicy(sizePolicy)
        self.label_clustering.setMinimumSize(QtCore.QSize(30, 0))
        self.label_clustering.setObjectName("label_clustering")
        self.gridLayout_2.addWidget(self.label_clustering, 5, 2, 1, 1)
        self.button_video_record = QtWidgets.QPushButton(self.verticalLayoutWidget_3)
        self.button_video_record.setObjectName("button_video_record")
        self.gridLayout_2.addWidget(self.button_video_record, 0, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 2, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 0, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_2)
        self.label_status = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.label_status.setFont(font)
        self.label_status.setAlignment(QtCore.Qt.AlignCenter)
        self.label_status.setObjectName("label_status")
        self.verticalLayout.addWidget(self.label_status)
        self.verticalLayout_3.addLayout(self.verticalLayout)
        self.label_pca_cluster = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_pca_cluster.sizePolicy().hasHeightForWidth())
        self.label_pca_cluster.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        self.label_pca_cluster.setFont(font)
        self.label_pca_cluster.setAlignment(QtCore.Qt.AlignCenter)
        self.label_pca_cluster.setObjectName("label_pca_cluster")
        self.verticalLayout_3.addWidget(self.label_pca_cluster)
        self.image_pca_cluster = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.image_pca_cluster.sizePolicy().hasHeightForWidth())
        self.image_pca_cluster.setSizePolicy(sizePolicy)
        self.image_pca_cluster.setAlignment(QtCore.Qt.AlignCenter)
        self.image_pca_cluster.setObjectName("image_pca_cluster")
        self.verticalLayout_3.addWidget(self.image_pca_cluster)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(sortingGui)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(720, 20, 911, 831))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.combo_cluster = QtWidgets.QComboBox(self.verticalLayoutWidget_2)
        self.combo_cluster.setObjectName("combo_cluster")
        self.verticalLayout_2.addWidget(self.combo_cluster)
        self.label_cluster_examples = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_cluster_examples.sizePolicy().hasHeightForWidth())
        self.label_cluster_examples.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        self.label_cluster_examples.setFont(font)
        self.label_cluster_examples.setAlignment(QtCore.Qt.AlignCenter)
        self.label_cluster_examples.setObjectName("label_cluster_examples")
        self.verticalLayout_2.addWidget(self.label_cluster_examples)
        self.image_cluster_examples = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.image_cluster_examples.setAlignment(QtCore.Qt.AlignCenter)
        self.image_cluster_examples.setObjectName("image_cluster_examples")
        self.verticalLayout_2.addWidget(self.image_cluster_examples)
        self.label_live_conveyor = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_live_conveyor.sizePolicy().hasHeightForWidth())
        self.label_live_conveyor.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        self.label_live_conveyor.setFont(font)
        self.label_live_conveyor.setAlignment(QtCore.Qt.AlignCenter)
        self.label_live_conveyor.setObjectName("label_live_conveyor")
        self.verticalLayout_2.addWidget(self.label_live_conveyor)
        self.image_live_conveyor = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.image_live_conveyor.setAlignment(QtCore.Qt.AlignCenter)
        self.image_live_conveyor.setObjectName("image_live_conveyor")
        self.verticalLayout_2.addWidget(self.image_live_conveyor)

        self.retranslateUi(sortingGui)
        QtCore.QMetaObject.connectSlotsByName(sortingGui)

    def retranslateUi(self, sortingGui):
        _translate = QtCore.QCoreApplication.translate
        sortingGui.setWindowTitle(_translate("sortingGui", "Autonomous Sorting"))
        self.label_connection.setText(_translate("sortingGui", "PushButton"))
        self.label_hardware_status.setText(_translate("sortingGui", "PushButton"))
        self.label_status_roboter.setText(_translate("sortingGui", "PushButton"))
        self.button_dobot_homing.setText(_translate("sortingGui", "Homing Robot"))
        self.button_dobot_standby.setText(_translate("sortingGui", "Standby"))
        self.button_connect_Hardware.setText(_translate("sortingGui", "Connect Hardware"))
        self.label_object_detection_method.setText(_translate("sortingGui", "PushButton"))
        self.radio_classic.setText(_translate("sortingGui", "Classic"))
        self.radio_yoloV7.setText(_translate("sortingGui", "YoloV7"))
        self.label_status_camera.setText(_translate("sortingGui", "PushButton"))
        self.label_seperator_connection.setText(_translate("sortingGui", "PushButton"))
        self.label_camera_connection.setText(_translate("sortingGui", "PushButton"))
        self.label_dobot_connection.setText(_translate("sortingGui", "PushButton"))
        self.label_conveyor_connection.setText(_translate("sortingGui", "PushButton"))
        self.label_status_conveyor.setText(_translate("sortingGui", "PushButton"))
        self.label_status_seperator.setText(_translate("sortingGui", "PushButton"))
        self.label_contour_method.setText(_translate("sortingGui", "PushButton"))
        self.radio_contour_cut.setText(_translate("sortingGui", "True"))
        self.label_phases.setText(_translate("sortingGui", "PushButton"))
        self.label_data_collection.setText(_translate("sortingGui", "PushButton"))
        self.check_feature_area.setText(_translate("sortingGui", "Area"))
        self.check_feature_aspect.setText(_translate("sortingGui", "Aspect"))
        self.check_feature_color.setText(_translate("sortingGui", "Color"))
        self.check_feature_length.setText(_translate("sortingGui", "Length"))
        self.check_feature_hu.setText(_translate("sortingGui", "Hu"))
        self.check_feature_extent.setText(_translate("sortingGui", "Extent"))
        self.check_feature_solidity.setText(_translate("sortingGui", "Solidity"))
        self.label_sorting.setText(_translate("sortingGui", "PushButton"))
        self.Button_Start_User_Feedback.setText(_translate("sortingGui", "Start User Feedback"))
        self.button_sorting.setText(_translate("sortingGui", "Start Sorting"))
        self.radio_2d.setText(_translate("sortingGui", "2D"))
        self.radio_3d.setText(_translate("sortingGui", "3D"))
        self.combo_clustering_method.setItemText(0, _translate("sortingGui", "KMeans"))
        self.combo_clustering_method.setItemText(1, _translate("sortingGui", "DBSCAN"))
        self.combo_clustering_method.setItemText(2, _translate("sortingGui", "MeanShift"))
        self.combo_clustering_method.setItemText(3, _translate("sortingGui", "Agglomerative"))
        self.SortingType.setItemText(0, _translate("sortingGui", "Manually Select Data"))
        self.SortingType.setItemText(1, _translate("sortingGui", "Autoencoder"))
        self.SortingType.setItemText(2, _translate("sortingGui", "Transformer"))
        self.label_data_loading.setText(_translate("sortingGui", "PushButton"))
        self.button_stop.setText(_translate("sortingGui", "Stop"))
        self.button_load_and_cluster_data.setText(_translate("sortingGui", "Load and Cluster Data"))
        self.button_data_collection.setText(_translate("sortingGui", "Data Collection Phase"))
        self.label_clustering.setText(_translate("sortingGui", "PushButton"))
        self.button_video_record.setText(_translate("sortingGui", "Train Background Subtractor"))
        self.label.setText(_translate("sortingGui", "PushButton"))
        self.label_2.setText(_translate("sortingGui", "Last Trained: "))
        self.label_status.setText(_translate("sortingGui", "PushButton"))
        self.label_pca_cluster.setText(_translate("sortingGui", "PushButton"))
        self.image_pca_cluster.setText(_translate("sortingGui", "PushButton"))
        self.label_cluster_examples.setText(_translate("sortingGui", "PushButton"))
        self.image_cluster_examples.setText(_translate("sortingGui", "PushButton"))
        self.label_live_conveyor.setText(_translate("sortingGui", "PushButton"))
        self.image_live_conveyor.setText(_translate("sortingGui", "PushButton"))

